# Stage 1: Build the application
FROM eclipse-temurin:21-jdk-alpine as builder

# Set the working directory
WORKDIR /app

# Copy Maven wrapper and project files
COPY .mvn/ .mvn
COPY mvnw pom.xml ./

# Download dependencies
RUN ./mvnw dependency:go-offline -B

# Copy the rest of the application source code
COPY src ./src

# Build the application
RUN ./mvnw package -DskipTests -B

# Stage 2: Create a minimal runtime image
FROM eclipse-temurin:21-jre-alpine

# Set the working directory
WORKDIR /app

# Install curl
RUN apk add --no-cache curl

# Copy the built JAR file from the builder stage
COPY --from=builder /app/target/api-gateway-0.0.1-SNAPSHOT.jar app.jar

# Expose the application port
EXPOSE 9000

# Run the application
ENTRYPOINT ["java", "-jar", "app.jar"]
