# Use an official lightweight Java image as the base image
FROM openjdk:21-jdk-slim

# Install curl
RUN apt-get update && apt-get install -y curl

# Set the working directory in the container
WORKDIR /app

# Copy the JAR file from the build directory to the container
COPY target/api-gateway-0.0.1-SNAPSHOT.jar api-gateway.jar

# Expose the application port configured in application.properties
EXPOSE 9000

# Set environment variables (if needed, adjust as required)
ENV SPRING_PROFILES_ACTIVE=prod

# Default command to run the JAR file
ENTRYPOINT ["java", "-jar", "api-gateway.jar"]
