# Use an OpenJDK image as the base
FROM eclipse-temurin:21-jdk-alpine

# Set the working directory in the container
WORKDIR /app

# Copy the Maven build artifact to the container
COPY target/product-service-0.0.1-SNAPSHOT.jar product-service.jar

# Expose the application's port
EXPOSE 8080

# Run the application
ENTRYPOINT ["java", "-jar", "product-service.jar"]
